    var employees = [
        {
            "id": 13,
            "firstName": "Erna",
            "lastName": "Yeaman",
            "businessArea": "FredCo",
            "number": 13,
            "domainQualifiedUserName": "FredCo\\Erna Yeaman",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 2,
            "leaver": false,
            "email": "erna.yeaman@acmehealth.co.uk"
        },
        {
            "id": 78,
            "firstName": "Kris",
            "lastName": "Womersley",
            "businessArea": "FredAcme",
            "number": 78,
            "domainQualifiedUserName": "FredAcme\\Kris Womersley",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 23,
            "leaver": false,
            "email": "kris.womersley@acme.co.uk"
        },
        {
            "id": 81,
            "firstName": "Lark",
            "lastName": "Wise",
            "businessArea": "FredCo",
            "number": 81,
            "domainQualifiedUserName": "FredCo\\Lark Wise",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "lark.wise@acme.com"
        },
        {
            "id": 55,
            "firstName": "Oswald",
            "lastName": "Wiggall",
            "businessArea": "FredLtd",
            "number": 55,
            "domainQualifiedUserName": "FredLtd\\Oswald Wiggall",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 31,
            "leaver": false,
            "email": "oswald.wiggall@acmehealth.co.uk"
        },
        {
            "id": 49,
            "firstName": "Shela",
            "lastName": "Whereat",
            "businessArea": "FredCo",
            "number": 49,
            "domainQualifiedUserName": "FredCo\\Shela Whereat",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 20,
            "leaver": false,
            "email": "shela.whereat@acme.co.uk"
        },
        {
            "id": 43,
            "firstName": "Brit",
            "lastName": "Watt",
            "businessArea": "FredLtd",
            "number": 43,
            "domainQualifiedUserName": "FredLtd\\Brit Watt",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 12,
            "leaver": false,
            "email": "brit.watt@acme.co.uk"
        },
        {
            "id": 21,
            "firstName": "Godiva",
            "lastName": "Vinsen",
            "businessArea": "FredCo",
            "number": 21,
            "domainQualifiedUserName": "FredCo\\Godiva Vinsen",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 6,
            "leaver": false,
            "email": "godiva.vinsen@acme.co.uk"
        },
        {
            "id": 98,
            "firstName": "Winslow",
            "lastName": "Ugoni",
            "businessArea": "FredAcme",
            "number": 98,
            "domainQualifiedUserName": "FredAcme\\Winslow Ugoni",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 28,
            "leaver": false,
            "email": "winslow.ugoni@acme.com"
        },
        {
            "id": 52,
            "firstName": "Brittani",
            "lastName": "Tilio",
            "businessArea": "FreddyStarCo",
            "number": 52,
            "domainQualifiedUserName": "FreddyStarCo\\Brittani Tilio",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 17,
            "leaver": false,
            "email": "brittani.tilio@acme.com"
        },
        {
            "id": 51,
            "firstName": "Wynnie",
            "lastName": "Thickpenny",
            "businessArea": "FredLtd",
            "number": 51,
            "domainQualifiedUserName": "FredLtd\\Wynnie Thickpenny",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 34,
            "leaver": false,
            "email": "wynnie.thickpenny@acmehealth.co.uk"
        },
        {
            "id": 97,
            "firstName": "Linet",
            "lastName": "Tellenbach",
            "businessArea": "FredCo",
            "number": 97,
            "domainQualifiedUserName": "FredCo\\Linet Tellenbach",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 25,
            "leaver": false,
            "email": "linet.tellenbach@acme.co.uk"
        },
        {
            "id": 42,
            "firstName": "Bearnard",
            "lastName": "Tames",
            "businessArea": "FredAcme",
            "number": 42,
            "domainQualifiedUserName": "FredAcme\\Bearnard Tames",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 15,
            "leaver": false,
            "email": "bearnard.tames@acme.com"
        },
        {
            "id": 6,
            "firstName": "Hartley",
            "lastName": "Sproston",
            "businessArea": "FredAcme",
            "number": 6,
            "domainQualifiedUserName": "FredAcme\\Hartley Sproston",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 2,
            "leaver": false,
            "email": "hartley.sproston@acme.co.uk"
        },
        {
            "id": 37,
            "firstName": "Chick",
            "lastName": "Soper",
            "businessArea": "FredCo",
            "number": 37,
            "domainQualifiedUserName": "FredCo\\Chick Soper",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 14,
            "leaver": false,
            "email": "chick.soper@acmehealth.co.uk"
        },
        {
            "id": 39,
            "firstName": "Sianna",
            "lastName": "Skoughman",
            "businessArea": "FredLtd",
            "number": 39,
            "domainQualifiedUserName": "FredLtd\\Sianna Skoughman",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 18,
            "leaver": false,
            "email": "sianna.skoughman@acmehealth.co.uk"
        },
        {
            "id": 41,
            "firstName": "Marisa",
            "lastName": "Simic",
            "businessArea": "FredCo",
            "number": 41,
            "domainQualifiedUserName": "FredCo\\Marisa Simic",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 15,
            "leaver": false,
            "email": "marisa.simic@acme.com"
        },
        {
            "id": 47,
            "firstName": "Amelie",
            "lastName": "Showell",
            "businessArea": "FredLtd",
            "number": 47,
            "domainQualifiedUserName": "FredLtd\\Amelie Showell",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 12,
            "leaver": false,
            "email": "amelie.showell@acme.co.uk"
        },
        {
            "id": 14,
            "firstName": "Irena",
            "lastName": "Segges",
            "businessArea": "FredAcme",
            "number": 14,
            "domainQualifiedUserName": "FredAcme\\Irena Segges",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 9,
            "leaver": false,
            "email": "irena.segges@acmehealth.co.uk"
        },
        {
            "id": 34,
            "firstName": "Adham",
            "lastName": "Ruoss",
            "businessArea": "FredAcme",
            "number": 34,
            "domainQualifiedUserName": "FredAcme\\Adham Ruoss",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 11,
            "leaver": false,
            "email": "adham.ruoss@acme.co.uk"
        },
        {
            "id": 10,
            "firstName": "Rebeca",
            "lastName": "Rimmington",
            "businessArea": "FredAcme",
            "number": 10,
            "domainQualifiedUserName": "FredAcme\\Rebeca Rimmington",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 4,
            "leaver": false,
            "email": "rebeca.rimmington@acme.com"
        },
        {
            "id": 83,
            "firstName": "Lanae",
            "lastName": "Rachuig",
            "businessArea": "FredLtd",
            "number": 83,
            "domainQualifiedUserName": "FredLtd\\Lanae Rachuig",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 51,
            "leaver": false,
            "email": "lanae.rachuig@acmehealth.co.uk"
        },
        {
            "id": 22,
            "firstName": "Thaxter",
            "lastName": "Probbin",
            "businessArea": "FredAcme",
            "number": 22,
            "domainQualifiedUserName": "FredAcme\\Thaxter Probbin",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 8,
            "leaver": false,
            "email": "thaxter.probbin@acme.com"
        },
        {
            "id": 2,
            "firstName": "Valry",
            "lastName": "Prisk",
            "businessArea": "FredAcme",
            "number": 2,
            "domainQualifiedUserName": "FredAcme\\Valry Prisk",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 1,
            "leaver": false,
            "email": "valry.prisk@acmehealth.co.uk"
        },
        {
            "id": 20,
            "firstName": "Victoir",
            "lastName": "Posnett",
            "businessArea": "FreddyStarCo",
            "number": 20,
            "domainQualifiedUserName": "FreddyStarCo\\Victoir Posnett",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 6,
            "leaver": false,
            "email": "victoir.posnett@acme.co.uk"
        },
        {
            "id": 99,
            "firstName": "Franni",
            "lastName": "Pipping",
            "businessArea": "FredLtd",
            "number": 99,
            "domainQualifiedUserName": "FredLtd\\Franni Pipping",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 25,
            "leaver": false,
            "email": "franni.pipping@acme.co.uk"
        },
        {
            "id": 15,
            "firstName": "Tania",
            "lastName": "Pepin",
            "businessArea": "FredLtd",
            "number": 15,
            "domainQualifiedUserName": "FredLtd\\Tania Pepin",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 4,
            "leaver": false,
            "email": "tania.pepin@acme.com"
        },
        {
            "id": 86,
            "firstName": "Hernando",
            "lastName": "Paxeford",
            "businessArea": "FredAcme",
            "number": 86,
            "domainQualifiedUserName": "FredAcme\\Hernando Paxeford",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "hernando.paxeford@acmehealth.co.uk"
        },
        {
            "id": 38,
            "firstName": "Cynthie",
            "lastName": "Parram",
            "businessArea": "FredAcme",
            "number": 38,
            "domainQualifiedUserName": "FredAcme\\Cynthie Parram",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 12,
            "leaver": false,
            "email": "cynthie.parram@acme.co.uk"
        },
        {
            "id": 3,
            "firstName": "Raquela",
            "lastName": "Palia",
            "businessArea": "FredLtd",
            "number": 3,
            "domainQualifiedUserName": "FredLtd\\Raquela Palia",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 1,
            "leaver": false,
            "email": "raquela.palia@acme.com"
        },
        {
            "id": 72,
            "firstName": "Danya",
            "lastName": "OBoyle",
            "businessArea": "FreddyStarCo",
            "number": 72,
            "domainQualifiedUserName": "FreddyStarCo\\Danya OBoyle",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "danya.oboyle@acme.com"
        },
        {
            "id": 16,
            "firstName": "Edee",
            "lastName": "Nesbitt",
            "businessArea": "FreddyStarCo",
            "number": 16,
            "domainQualifiedUserName": "FreddyStarCo\\Edee Nesbitt",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 4,
            "leaver": false,
            "email": "edee.nesbitt@acme.com"
        },
        {
            "id": 31,
            "firstName": "Grover",
            "lastName": "Milley",
            "businessArea": "FredLtd",
            "number": 31,
            "domainQualifiedUserName": "FredLtd\\Grover Milley",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 14,
            "leaver": false,
            "email": "grover.milley@acmehealth.co.uk"
        },
        {
            "id": 60,
            "firstName": "Tremaine",
            "lastName": "McKea",
            "businessArea": "FreddyStarCo",
            "number": 60,
            "domainQualifiedUserName": "FreddyStarCo\\Tremaine McKea",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 17,
            "leaver": false,
            "email": "tremaine.mckea@acme.com"
        },
        {
            "id": 30,
            "firstName": "Ethelind",
            "lastName": "Matyja",
            "businessArea": "FredAcme",
            "number": 30,
            "domainQualifiedUserName": "FredAcme\\Ethelind Matyja",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 11,
            "leaver": false,
            "email": "ethelind.matyja@acme.co.uk"
        },
        {
            "id": 69,
            "firstName": "Brenna",
            "lastName": "Managh",
            "businessArea": "FredCo",
            "number": 69,
            "domainQualifiedUserName": "FredCo\\Brenna Managh",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "brenna.managh@acme.com"
        },
        {
            "id": 80,
            "firstName": "Herbert",
            "lastName": "MacPharlain",
            "businessArea": "FreddyStarCo",
            "number": 80,
            "domainQualifiedUserName": "FreddyStarCo\\Herbert MacPharlain",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 23,
            "leaver": false,
            "email": "herbert.macpharlain@acme.co.uk"
        },
        {
            "id": 26,
            "firstName": "Korey",
            "lastName": "Mackney",
            "businessArea": "FredAcme",
            "number": 26,
            "domainQualifiedUserName": "FredAcme\\Korey Mackney",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 11,
            "leaver": false,
            "email": "korey.mackney@acme.co.uk"
        },
        {
            "id": 63,
            "firstName": "Albrecht",
            "lastName": "MacConnal",
            "businessArea": "FredLtd",
            "number": 63,
            "domainQualifiedUserName": "FredLtd\\Albrecht MacConnal",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 37,
            "leaver": false,
            "email": "albrecht.macconnal@acmehealth.co.uk"
        },
        {
            "id": 67,
            "firstName": "Johannah",
            "lastName": "Leghorn",
            "businessArea": "FredLtd",
            "number": 67,
            "domainQualifiedUserName": "FredLtd\\Johannah Leghorn",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 40,
            "leaver": false,
            "email": "johannah.leghorn@acmehealth.co.uk"
        },
        {
            "id": 88,
            "firstName": "Rorke",
            "lastName": "Laxe",
            "businessArea": "FreddyStarCo",
            "number": 88,
            "domainQualifiedUserName": "FreddyStarCo\\Rorke Laxe",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "rorke.laxe@acmehealth.co.uk"
        },
        {
            "id": 68,
            "firstName": "Katleen",
            "lastName": "Lawlan",
            "businessArea": "FreddyStarCo",
            "number": 68,
            "domainQualifiedUserName": "FreddyStarCo\\Katleen Lawlan",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 40,
            "leaver": false,
            "email": "katleen.lawlan@acmehealth.co.uk"
        },
        {
            "id": 71,
            "firstName": "Sarette",
            "lastName": "Lared",
            "businessArea": "FredLtd",
            "number": 71,
            "domainQualifiedUserName": "FredLtd\\Sarette Lared",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "sarette.lared@acme.com"
        },
        {
            "id": 24,
            "firstName": "Leonore",
            "lastName": "Lansley",
            "businessArea": "FreddyStarCo",
            "number": 24,
            "domainQualifiedUserName": "FreddyStarCo\\Leonore Lansley",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 13,
            "leaver": false,
            "email": "leonore.lansley@acmehealth.co.uk"
        },
        {
            "id": 87,
            "firstName": "Norean",
            "lastName": "Laidlow",
            "businessArea": "FredLtd",
            "number": 87,
            "domainQualifiedUserName": "FredLtd\\Norean Laidlow",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 28,
            "leaver": false,
            "email": "norean.laidlow@acme.com"
        },
        {
            "id": 17,
            "firstName": "Idaline",
            "lastName": "Laidlaw",
            "businessArea": "FredCo",
            "number": 17,
            "domainQualifiedUserName": "FredCo\\Idaline Laidlaw",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 4,
            "leaver": false,
            "email": "idaline.laidlaw@acme.com"
        },
        {
            "id": 56,
            "firstName": "Matelda",
            "lastName": "Knowlys",
            "businessArea": "FreddyStarCo",
            "number": 56,
            "domainQualifiedUserName": "FreddyStarCo\\Matelda Knowlys",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 31,
            "leaver": false,
            "email": "matelda.knowlys@acmehealth.co.uk"
        },
        {
            "id": 93,
            "firstName": "Donal",
            "lastName": "Keslake",
            "businessArea": "FredCo",
            "number": 93,
            "domainQualifiedUserName": "FredCo\\Donal Keslake",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 28,
            "leaver": false,
            "email": "donal.keslake@acme.com"
        },
       {
            "id": 73,
            "firstName": "Dickie",
            "lastName": "Keenor",
            "businessArea": "FredCo",
            "number": 73,
            "domainQualifiedUserName": "FredCo\\Dickie Keenor",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "dickie.keenor@acme.com"
        },
        {
            "id": 100,
            "firstName": "Renee",
            "lastName": "Jolliman",
            "businessArea": "FreddyStarCo",
            "number": 100,
            "domainQualifiedUserName": "FreddyStarCo\\Renee Jolliman",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 25,
            "leaver": false,
            "email": "renee.jolliman@acme.co.uk"
        },
        {
            "id": 76,
            "firstName": "Marian",
            "lastName": "Jennison",
            "businessArea": "FreddyStarCo",
            "number": 76,
            "domainQualifiedUserName": "FreddyStarCo\\Marian Jennison",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 46,
            "leaver": false,
            "email": "marian.jennison@acmehealth.co.uk"
        },
        {
            "id": 66,
            "firstName": "Kirby",
            "lastName": "Janc",
            "businessArea": "FredAcme",
            "number": 66,
            "domainQualifiedUserName": "FredAcme\\Kirby Janc",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 21,
            "leaver": false,
            "email": "kirby.janc@acme.co.uk"
        },
        {
            "id": 62,
            "firstName": "Bordy",
            "lastName": "Hummerston",
            "businessArea": "FredAcme",
            "number": 62,
            "domainQualifiedUserName": "FredAcme\\Bordy Hummerston",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 37,
            "leaver": false,
            "email": "bordy.hummerston@acmehealth.co.uk"
        },
        {
            "id": 29,
            "firstName": "Cori",
            "lastName": "Hogertie",
            "businessArea": "FredCo",
            "number": 29,
            "domainQualifiedUserName": "FredCo\\Cori OHogertie",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 10,
            "leaver": false,
            "email": "cori.ohogertie@acme.com"
        },
        {
            "id": 65,
            "firstName": "Dominik",
            "lastName": "Heyball",
            "businessArea": "FredCo",
            "number": 65,
            "domainQualifiedUserName": "FredCo\\Dominik Heyball",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 39,
            "leaver": false,
            "email": "dominik.heyball@acmehealth.co.uk"
        },
        {
            "id": 46,
            "firstName": "Harp",
            "lastName": "Hadcock",
            "businessArea": "FredAcme",
            "number": 46,
            "domainQualifiedUserName": "FredAcme\\Harp Hadcock",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 19,
            "leaver": false,
            "email": "harp.hadcock@acmehealth.co.uk"
        },
        {
            "id": 94,
            "firstName": "Christin",
            "lastName": "Gunderson",
            "businessArea": "FredAcme",
            "number": 94,
            "domainQualifiedUserName": "FredAcme\\Christin Gunderson",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "christin.gunderson@acmehealth.co.uk"
        },
        {
            "id": 4,
            "firstName": "Gerhard",
            "lastName": "Guiso",
            "businessArea": "FreddyStarCo",
            "number": 4,
            "domainQualifiedUserName": "FreddyStarCo\\Gerhard Guiso",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 3,
            "leaver": false,
            "email": "gerhard.guiso@acme.com"
        },
        {
            "id": 19,
            "firstName": "Brady",
            "lastName": "Groocock",
            "businessArea": "FredLtd",
            "number": 19,
            "domainQualifiedUserName": "FredLtd\\Brady Groocock",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 9,
            "leaver": false,
            "email": "brady.groocock@acmehealth.co.uk"
        },
        {
            "id": 89,
            "firstName": "Gail",
            "lastName": "Grimbaldeston",
            "businessArea": "FredCo",
            "number": 89,
            "domainQualifiedUserName": "FredCo\\Gail Grimbaldeston",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "gail.grimbaldeston@acmehealth.co.uk"
        },
        {
            "id": 25,
            "firstName": "Gideon",
            "lastName": "Goodlake",
            "businessArea": "FredCo",
            "number": 25,
            "domainQualifiedUserName": "FredCo\\Gideon Goodlake",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 7,
            "leaver": false,
            "email": "gideon.goodlake@acme.co.uk"
        },
        {
            "id": 8,
            "firstName": "Maje",
            "lastName": "Going",
            "businessArea": "FreddyStarCo",
            "number": 8,
            "domainQualifiedUserName": "FreddyStarCo\\Maje Going",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 3,
            "leaver": false,
            "email": "maje.going@acme.com"
        },
        {
            "id": 12,
            "firstName": "Sigrid",
            "lastName": "Goble",
            "businessArea": "FreddyStarCo",
            "number": 12,
            "domainQualifiedUserName": "FreddyStarCo\\Sigrid Goble",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 5,
            "leaver": false,
            "email": "sigrid.goble@acme.co.uk"
        },
        {
            "id": 53,
            "firstName": "Raven",
            "lastName": "Gloves",
            "businessArea": "FredCo",
            "number": 53,
            "domainQualifiedUserName": "FredCo\\Raven Gloves",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 34,
            "leaver": false,
            "email": "raven.gloves@acmehealth.co.uk"
        },
        {
            "id": 75,
            "firstName": "Marena",
            "lastName": "Girling",
            "businessArea": "FredLtd",
            "number": 75,
            "domainQualifiedUserName": "FredLtd\\Marena Girling",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 44,
            "leaver": false,
            "email": "marena.girling@acmehealth.co.uk"
        },
        {
            "id": 33,
            "firstName": "Elayne",
            "lastName": "Gilbank",
            "businessArea": "FredCo",
            "number": 33,
            "domainQualifiedUserName": "FredCo\\Elayne Gilbank",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 14,
            "leaver": false,
            "email": "elayne.gilbank@acmehealth.co.uk"
        },
        {
            "id": 57,
            "firstName": "Nell",
            "lastName": "Gherardi",
            "businessArea": "FredCo",
            "number": 57,
            "domainQualifiedUserName": "FredCo\\Nell Gherardi",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 33,
            "leaver": false,
            "email": "nell.gherardi@acmehealth.co.uk"
        },
        {
            "id": 59,
            "firstName": "Israel",
            "lastName": "Gannicleff",
            "businessArea": "FredLtd",
            "number": 59,
            "domainQualifiedUserName": "FredLtd\\Israel Gannicleff",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 33,
            "leaver": false,
            "email": "israel.gannicleff@acmehealth.co.uk"
        },
        {
            "id": 74,
            "firstName": "Rebeca",
            "lastName": "Freestone",
            "businessArea": "FredAcme",
            "number": 74,
            "domainQualifiedUserName": "FredAcme\\Rebeca Freestone",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 23,
            "leaver": false,
            "email": "rebeca.freestone@acme.co.uk"
        },
        {
            "id": 44,
            "firstName": "Salvador",
            "lastName": "Fontenot",
            "businessArea": "FreddyStarCo",
            "number": 44,
            "domainQualifiedUserName": "FreddyStarCo\\Salvador Fontenot",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 19,
            "leaver": false,
            "email": "salvador.fontenot@acmehealth.co.uk"
        },
        {
            "id": 77,
            "firstName": "Lacee",
            "lastName": "Ferrand",
            "businessArea": "FredCo",
            "number": 77,
            "domainQualifiedUserName": "FredCo\\Lacee Ferrand",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 46,
            "leaver": false,
            "email": "lacee.ferrand@acmehealth.co.uk"
        },
        {
            "id": 48,
            "firstName": "Deirdre",
            "lastName": "Fane",
            "businessArea": "FreddyStarCo",
            "number": 48,
            "domainQualifiedUserName": "FreddyStarCo\\Deirdre Fane",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 16,
            "leaver": false,
            "email": "deirdre.fane@acme.com"
        },
        {
            "id": 96,
            "firstName": "Dalis",
            "lastName": "Eden",
            "businessArea": "FreddyStarCo",
            "number": 96,
            "domainQualifiedUserName": "FreddyStarCo\\Dalis Eden",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 25,
            "leaver": false,
            "email": "dalis.eden@acme.co.uk"
        },
        {
            "id": 84,
            "firstName": "Elden",
            "lastName": "Durrance",
            "businessArea": "FreddyStarCo",
            "number": 84,
            "domainQualifiedUserName": "FreddyStarCo\\Elden Durrance",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 22,
            "leaver": false,
            "email": "elden.durrance@acme.com"
        },
        {
            "id": 50,
            "firstName": "Bentlee",
            "lastName": "Durrance",
            "businessArea": "FredAcme",
            "number": 50,
            "domainQualifiedUserName": "FredAcme\\Bentlee Durrance",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 20,
            "leaver": false,
            "email": "bentlee.durrance@acme.co.uk"
        },
        {
            "id": 40,
            "firstName": "Chas",
            "lastName": "Ditch",
            "businessArea": "FreddyStarCo",
            "number": 40,
            "domainQualifiedUserName": "FreddyStarCo\\Chas Ditch",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 18,
            "leaver": false,
            "email": "chas.ditch@acmehealth.co.uk"
        },
        {
            "id": 70,
            "firstName": "Torrin",
            "lastName": "Del Monte",
            "businessArea": "FredAcme",
            "number": 70,
            "domainQualifiedUserName": "FredAcme\\Torrin Del Monte",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 40,
            "leaver": false,
            "email": "torrin.del monte@acmehealth.co.uk"
        },
        {
            "id": 28,
            "firstName": "Jared",
            "lastName": "Davenall",
            "businessArea": "FreddyStarCo",
            "number": 28,
            "domainQualifiedUserName": "FreddyStarCo\\Jared Davenall",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 8,
            "leaver": false,
            "email": "jared.davenall@acme.com"
        },
        {
            "id": 92,
            "firstName": "Edgardo",
            "lastName": "Dakhno",
            "businessArea": "FreddyStarCo",
            "number": 92,
            "domainQualifiedUserName": "FreddyStarCo\\Edgardo Dakhno",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "edgardo.dakhno@acmehealth.co.uk"
        },
        {
            "id": 1,
            "firstName": "Aubrey",
            "lastName": "Cushelly",
            "businessArea": "FredCo",
            "number": 1,
            "domainQualifiedUserName": "FredCo\\Aubrey Cushelly",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 0,
            "leaver": false,
            "email": "aubrey.cushelly@acme.co.uk"
        },
        {
            "id": 82,
            "firstName": "Claire",
            "lastName": "Cribbin",
            "businessArea": "FredAcme",
            "number": 82,
            "domainQualifiedUserName": "FredAcme\\Claire Cribbin",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 23,
            "leaver": false,
            "email": "claire.cribbin@acme.co.uk"
        },
        {
            "id": 18,
            "firstName": "Kimberlee",
            "lastName": "Chestney",
            "businessArea": "FredAcme",
            "number": 18,
            "domainQualifiedUserName": "FredAcme\\Kimberlee Chestney",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 9,
            "leaver": false,
            "email": "kimberlee.chestney@acmehealth.co.uk"
        },
        {
            "id": 9,
            "firstName": "Eugenie",
            "lastName": "Chatelain",
            "businessArea": "FredCo",
            "number": 9,
            "domainQualifiedUserName": "FredCo\\Eugenie Chatelain",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 2,
            "leaver": false,
            "email": "eugenie.chatelain@acmehealth.co.uk"
        },
        {
            "id": 64,
            "firstName": "Ally",
            "lastName": "Challin",
            "businessArea": "FreddyStarCo",
            "number": 64,
            "domainQualifiedUserName": "FreddyStarCo\\Ally Challin",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 39,
            "leaver": false,
            "email": "ally.challin@acmehealth.co.uk"
        },
        {
            "id": 91,
            "firstName": "Ardine",
            "lastName": "Cammish",
            "businessArea": "FredLtd",
            "number": 91,
            "domainQualifiedUserName": "FredLtd\\Ardine Cammish",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 25,
            "leaver": false,
            "email": "ardine.cammish@acme.co.uk"
        },
        {
            "id": 54,
            "firstName": "Maxi",
            "lastName": "Calderwood",
            "businessArea": "FredAcme",
            "number": 54,
            "domainQualifiedUserName": "FredAcme\\Maxi Calderwood",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 20,
            "leaver": false,
            "email": "maxi.calderwood@acme.co.uk"
        },
        {
            "id": 95,
            "firstName": "Otho",
            "lastName": "Bunclark",
            "businessArea": "FredLtd",
            "number": 95,
            "domainQualifiedUserName": "FredLtd\\Otho Bunclark",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "otho.bunclark@acmehealth.co.uk"
        },
        {
            "id": 45,
            "firstName": "Hube",
            "lastName": "Bum",
            "businessArea": "FredCo",
            "number": 45,
            "domainQualifiedUserName": "FredCo\\Hube Bum",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 16,
            "leaver": false,
            "email": "hube.bum@acme.com"
        },
        {
            "id": 85,
            "firstName": "Halie",
            "lastName": "Brockie",
            "businessArea": "FredCo",
            "number": 85,
            "domainQualifiedUserName": "FredCo\\Halie Brockie",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "halie.brockie@acmehealth.co.uk"
        },
        {
            "id": 36,
            "firstName": "Isis",
            "lastName": "Bradick",
            "businessArea": "FreddyStarCo",
            "number": 36,
            "domainQualifiedUserName": "FreddyStarCo\\Isis Bradick",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 10,
            "leaver": false,
            "email": "isis.bradick@acme.com"
        },
        {
            "id": 27,
            "firstName": "Vlad",
            "lastName": "Boswood",
            "businessArea": "FredLtd",
            "number": 27,
            "domainQualifiedUserName": "FredLtd\\Vlad Boswood",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 11,
            "leaver": false,
            "email": "vlad.boswood@acme.co.uk"
        },
        {
            "id": 11,
            "firstName": "Cynthea",
            "lastName": "Blodgett",
            "businessArea": "FredLtd",
            "number": 11,
            "domainQualifiedUserName": "FredLtd\\Cynthea Blodgett",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 5,
            "leaver": false,
            "email": "cynthea.blodgett@acme.co.uk"
       },
        {
            "id": 90,
            "firstName": "Libbey",
            "lastName": "Blakiston",
            "businessArea": "FredAcme",
            "number": 90,
            "domainQualifiedUserName": "FredAcme\\Libbey Blakiston",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 53,
            "leaver": false,
            "email": "libbey.blakiston@acmehealth.co.uk"
        },
        {
            "id": 5,
            "firstName": "Haven",
            "lastName": "Berford",
            "businessArea": "FredCo",
            "number": 5,
            "domainQualifiedUserName": "FredCo\\Haven Berford",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 2,
            "leaver": false,
            "email": "haven.berford@acme.co.uk"
        },
        {
            "id": 32,
            "firstName": "Ario",
            "lastName": "Beine",
            "businessArea": "FreddyStarCo",
            "number": 32,
            "domainQualifiedUserName": "FreddyStarCo\\Ario Beine",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 11,
            "leaver": false,
            "email": "ario.beine@acme.co.uk"
        },
        {
            "id": 7,
            "firstName": "Kerstin",
            "lastName": "Beaumont",
            "businessArea": "FredLtd",
            "number": 7,
            "domainQualifiedUserName": "FredLtd\\Kerstin Beaumont",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 1,
            "leaver": false,
            "email": "kerstin.beaumont@acme.co.uk"
        },
        {
            "id": 79,
            "firstName": "Aleksandr",
            "lastName": "Baser",
            "businessArea": "FredLtd",
            "number": 79,
            "domainQualifiedUserName": "FredLtd\\Aleksandr Baser",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 51,
            "leaver": false,
            "email": "aleksandr.baser@acmehealth.co.uk"
        },
        {
            "id": 58,
            "firstName": "Bobette",
            "lastName": "Bartolomucci",
            "businessArea": "FredAcme",
            "number": 58,
            "domainQualifiedUserName": "FredAcme\\Bobette Bartolomucci",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 21,
            "leaver": false,
            "email": "bobette.bartolomucci@acme.co.uk"
        },
        {
            "id": 35,
            "firstName": "Shane",
            "lastName": "Astling",
            "businessArea": "FredLtd",
            "number": 35,
            "domainQualifiedUserName": "FredLtd\\Shane Astling",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 12,
            "leaver": false,
            "email": "shane.astling@acme.co.uk"
        },
        {
            "id": 23,
            "firstName": "Laurice",
            "lastName": "Aslum",
            "businessArea": "FredLtd",
            "number": 23,
            "domainQualifiedUserName": "FredLtd\\Laurice Aslum",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 7,
            "leaver": false,
            "email": "laurice.aslum@acme.co.uk"
        },
        {
            "id": 61,
            "firstName": "Herb",
            "lastName": "Anniwell",
            "businessArea": "FredCo",
            "number": 61,
            "domainQualifiedUserName": "FredCo\\Herb Anniwell",
            "createdDate": "2001-08-11T10:36:00",
            "managerId": 37,
            "leaver": false,
            "email": "herb.anniwell@acmehealth.co.uk"
        }
    ]
    
    module.exports = employees;


